const SUCCESS = 0
const INVALID_PARAMS = 40000
const INTERNAL_ERROR = 40001
const PREPARE_UPLOAD_ERROR = 50000
const GET_FILEINFO_FROM_DB_ERROR = 50001
const CREATE_DOWNLOAD_FILE_FAILED = 50002
const DOWNLOAD_BLOCK_FAILED = 50003
const GET_FILE_STATE_ERROR = 50004
const WRITE_FILE_DATA_FAILED = 50005
const DECRYPT_FILE_FAILED = 50006
const DECRYPT_WRONG_PASSWORD = 50007

module.exports = {
    SUCCESS,
    INVALID_PARAMS,
    INTERNAL_ERROR,
    PREPARE_UPLOAD_ERROR,
    GET_FILEINFO_FROM_DB_ERROR,
    CREATE_DOWNLOAD_FILE_FAILED,
    DOWNLOAD_BLOCK_FAILED,
    GET_FILE_STATE_ERROR,
    WRITE_FILE_DATA_FAILED,
    DECRYPT_FILE_FAILED,
    DECRYPT_WRONG_PASSWORD,
}